# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blast < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/blast"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.15/blast_0.1.15_darwin_amd64.tar.gz"
      sha256 "aea534461571f0de6c69de45d8097bf40f24625573977c436af2d776ef329f12"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.15/blast_0.1.15_darwin_arm64.tar.gz"
      sha256 "3b82092019879ee726fa152af54a7276b497caa5912a27993da29ab72b4fc00b"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.15/blast_0.1.15_linux_amd64.tar.gz"
      sha256 "7097cf80762c923e5a4c5020f61b36bd54b95d2e679cd01c31b390672f166e6e"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.15/blast_0.1.15_linux_arm64.tar.gz"
      sha256 "7c051c1fdf91280913b71e1a587d2f3489e8b577abca2ee9789d8915603b6bc2"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  test do
    system "#{bin}/blast", "version"
  end
end
