# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Blast < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/blast"
  version "0.1.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.16/blast_0.1.16_darwin_amd64.tar.gz"
      sha256 "223ef9520fd8d1bdd70bfa6b8a1c0c717d351e8854a871a38a30a54825e3357d"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.16/blast_0.1.16_darwin_arm64.tar.gz"
      sha256 "b5e1b4f891756be23c10eff24acfb2aaf691bddff585953965869d8e72cfa4bd"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.16/blast_0.1.16_linux_amd64.tar.gz"
      sha256 "16a7bb478512d4787a9b2382ab8dc532a18347488b30dd823584b1bb1aef3d6c"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/blast/releases/download/v0.1.16/blast_0.1.16_linux_arm64.tar.gz"
      sha256 "24d89f288ef70fbc26eb5d4dabceff5c2bc4e6d6280c68c0b047515b4ca77e31"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  def caveats
    <<~EOS
      "blast" is also the name of an unrelated homebrew-core formula
      (NCBI's BLAST bioinformatics tool). Always install/upgrade this
      one by its fully-qualified name:
        brew install AlbertoBarrago/tap/blast
      A bare "brew install blast" resolves to homebrew-core instead.
    EOS
  end

  test do
    system "#{bin}/blast", "version"
  end
end
