# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changeblast < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/changeblast"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.1/changeblast_0.1.1_darwin_amd64.tar.gz"
      sha256 "679090fa5c6ffd4a29eb005ed6f1be6491b120e42128bf1584b3724f73eaddc0"

      define_method(:install) do
        bin.install "blast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.1/changeblast_0.1.1_darwin_arm64.tar.gz"
      sha256 "42ef50c355e15ab46bc87fa6c7309cb12218129b0916fc0198920d58494630df"

      define_method(:install) do
        bin.install "blast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.1/changeblast_0.1.1_linux_amd64.tar.gz"
      sha256 "c4a4c01d2acb55bdfd935672568172f53185e523f3f91d6307a236c83ffecb78"
      define_method(:install) do
        bin.install "blast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.1/changeblast_0.1.1_linux_arm64.tar.gz"
      sha256 "1f2b5f7f3b39b2592da74bbf9352a4a12f510b16e3e6814d9c2293e444c72774"
      define_method(:install) do
        bin.install "blast"
      end
    end
  end

  test do
    system "#{bin}/blast", "version"
  end
end
