# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changeblast < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/changeblast"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.5/changeblast_0.1.5_darwin_amd64.tar.gz"
      sha256 "84990d26bc16869f0f4bd00c0ee43177596ae26dc5f140f623b677d5cd3a7fc5"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.5/changeblast_0.1.5_darwin_arm64.tar.gz"
      sha256 "290791d992070f26cb1a91c6b5e496e01c6753d9098e8ffb0aa3f08f4154dc08"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.5/changeblast_0.1.5_linux_amd64.tar.gz"
      sha256 "b1bd2796051c2bc0336fa34534d7f66c1aab2506f3af8cf09107f1fa77a69b74"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.5/changeblast_0.1.5_linux_arm64.tar.gz"
      sha256 "34b52c6c2b6ff78a448d1c4c4b6e37fe3c48b4a94583a98ce982f418e32552df"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  test do
    system "#{bin}/blast", "version"
  end
end
