# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Changeblast < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/changeblast"
  version "0.1.11"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.11/changeblast_0.1.11_darwin_amd64.tar.gz"
      sha256 "15cfdca1b4216653a851e54df7145a95ce9c0b5379a95f9699f82cbae2f06a6b"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.11/changeblast_0.1.11_darwin_arm64.tar.gz"
      sha256 "9b6a44ba77bbe1e8fe8ca89c8f4e4a4a8d6594e2e182b89e7c91f4204f1e24ca"

      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.11/changeblast_0.1.11_linux_amd64.tar.gz"
      sha256 "967ea585223163253ef8449a75277e053a0892cff9de98afd63d1edd1dc8d952"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/changeblast/releases/download/v0.1.11/changeblast_0.1.11_linux_arm64.tar.gz"
      sha256 "a0a34e5eae4b6c2902d4844415db727c309c8feee204d5441b0569499b14fcac"
      define_method(:install) do
        bin.install "blast"
        man1.install Dir["*.1"]
      end
    end
  end

  test do
    system "#{bin}/blast", "version"
  end
end
