# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Impactline < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/impactline"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/impactline/releases/download/v0.1.17/impactline_0.1.17_darwin_amd64.tar.gz"
      sha256 "ef45188f8381c98ac78f20816b1b5f8bbb28c0f8d4a841a4df0202658668acbf"

      define_method(:install) do
        bin.install "impactline"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/impactline/releases/download/v0.1.17/impactline_0.1.17_darwin_arm64.tar.gz"
      sha256 "8a7088045705f848492e00f212ea49c9028e1c396e34eb4d7d349ddf87490f69"

      define_method(:install) do
        bin.install "impactline"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/impactline/releases/download/v0.1.17/impactline_0.1.17_linux_amd64.tar.gz"
      sha256 "dfe0830e20230a452a734c2fe89ba5b087e8076d3257bc24b2720c06b1aef230"
      define_method(:install) do
        bin.install "impactline"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/impactline/releases/download/v0.1.17/impactline_0.1.17_linux_arm64.tar.gz"
      sha256 "003ca67556fb688a76b0c3c2699edbacc8669562e5105ce9b9df6e66ed8d3208"
      define_method(:install) do
        bin.install "impactline"
        man1.install Dir["*.1"]
      end
    end
  end

  test do
    system "#{bin}/impactline", "version"
  end
end
