# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Serval < Formula
  desc "Local-first CLI that estimates the blast radius of a code change"
  homepage "https://github.com/AlbertoBarrago/serval"
  version "0.1.20"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlbertoBarrago/serval/releases/download/v0.1.20/serval_0.1.20_darwin_amd64.tar.gz"
      sha256 "865ef98e6d3a2dd2cd236378e670441d886e400cfb322b2de996113d152cdaff"

      define_method(:install) do
        bin.install "serval"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlbertoBarrago/serval/releases/download/v0.1.20/serval_0.1.20_darwin_arm64.tar.gz"
      sha256 "86c018b3d49a6fa0ef66ddfbce58750b3a5494c164f6e9c28a75a2ef1969b755"

      define_method(:install) do
        bin.install "serval"
        man1.install Dir["*.1"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/serval/releases/download/v0.1.20/serval_0.1.20_linux_amd64.tar.gz"
      sha256 "0ea6c67a33223194529e0e04e8ea7a5b6c4dfa01743db5739308aa3051e029b2"
      define_method(:install) do
        bin.install "serval"
        man1.install Dir["*.1"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlbertoBarrago/serval/releases/download/v0.1.20/serval_0.1.20_linux_arm64.tar.gz"
      sha256 "a5b96445a79443125bf8aa7fb65403e890ee954ecf829cf3bea312415b57f368"
      define_method(:install) do
        bin.install "serval"
        man1.install Dir["*.1"]
      end
    end
  end

  test do
    system "#{bin}/serval", "version"
  end
end
